### ISSUE TITLE
Unable to access CDMamba Weights

### ISSUE THREAD

**Issue by JoyLinWQ** [zmoka-zht/CDMamba#13]
Hi @zmoka-zht , are you able to share the CDMamba Weights via Google Drive please? Thank you.

**Comment by zmoka-zht** [comment]
Thank you for your comments. We've added a Google Drive download link https://drive.google.com/file/d/1ImTvjN-vPnlJtVwfemzeHWcjoNMFsrS7/view?usp=drive_link

**Comment by JoyLinWQ** [comment]
Please grant drive access too, thank you @zmoka-zht !

**Comment by zmoka-zht** [comment]
We have changed the permissions and you have access. Thank you for your attention.
