### ISSUE TITLE
ImportError: cannot import name 'bimamba_inner_fn' from 'mamba_ssm.ops.selective_scan_interface'

### ISSUE THREAD

**Issue by take-off-xyz** [zmoka-zht/CDMamba#2]
![p](https://github.com/zmoka-zht/CDMamba/assets/102784535/4f050929-1fc0-41b3-96ff-99485d12cf68)

**Comment by take-off-xyz** [comment]
python=3.10 torch=2.1.0 mamba-ssh=1.2.0.post1

**Comment by zmoka-zht** [comment]
If the mamba package is imported successfully, no error is reported. Check whether mamba and its corresponding packages are imported successfully. You can also download the corresponding package according to https://github.com/state-spaces/mamba/releases.

**Comment by take-off-xyz** [comment]
![pic](https://github.com/zmoka-zht/CDMamba/assets/102784535/021134f6-3db2-4c5d-876c-2e52ae58770b)
I installed mamba-ssh=1.2.0.post1 successfully, but can't import these two, I found there are no these two in mamba_ssm.ops.selective_scan_interface.py. Sincerely look forward to your help.

**Comment by zmoka-zht** [comment]
You should install mamba-ssm. You can install mamba packages from https://github.com/state-spaces/mamba/releases according to the environment.

**Comment by BruceLin30** [comment]
解决了吗老哥。

**Comment by take-off-xyz** [comment]
> 解决了吗老哥。

没有...不知道该咋弄了，换了几个mamba-ssm的版本也不行

**Comment by BruceLin30** [comment]
是这样的，应该是版本太老了，我从icml2024，vison mamba，这个文章的github库里面下载了mamba-ssm放到目录里面，就可以不用install mamba-ssm了。

**Comment by take-off-xyz** [comment]
What's the difference between bimamba_type == "v2" and bimamba_type == "none" ? when bimamba_type == "v2", I can't import 'bimamba_inner_fn, mamba_inner_fn_no_out_proj' form mamba_ssm.ops.selective_scan_interface, when bimamba_type == "none", I can run your model. Look forward to your answer, because I really want to use your paper for contrast experiment.

![20240717](https://github.com/user-attachments/assets/4d697c88-24e3-4a2a-b011-ae693aeb57b1)

**Comment by Charm11492** [comment]
> What's the difference between bimamba_type == "v2" and bimamba_type == "none" ? when bimamba_type == "v2", I can't import 'bimamba_inner_fn, mamba_inner_fn_no_out_proj' form mamba_ssm.ops.selective_scan_interface, when bimamba_type == "none", I can run your model. Look forward to your answer, because I really want to use your paper for contrast experiment.
> 
> ![20240717](https://private-user-images.githubusercontent.com/102784535/349417142-4d697c88-24e3-4a2a-b011-ae693aeb57b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyODYxMDEsIm5iZiI6MTcyMTI4NTgwMSwicGF0aCI6Ii8xMDI3ODQ1MzUvMzQ5NDE3MTQyLTRkNjk3Yzg4LTI0ZTMtNGEyYS1iMDExLWFlNjkzYWViNTdiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQwNjU2NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTBlZTg2ZjYyMGQ2YWZhODM1ZmNjNTk0ZmZhYTc3ZjJmMjMwZmQyZjQ1NDRjYTYyY2M4ZTZjNGM2MzAxNWQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._kIt_qPO25Rl3z5jQZjswEQStlEQSelRDyhRKPQDVjc)


138/5000
I met the same problem as you. I found that the mamba_ssm installed in the conda environment needs to be replaced with the mamba_ssm in the official project of vision mamba. See the https://blog.csdn.net/weixin_45667052/article/details/136311600

**Comment by Charm11492** [comment]
> I met the same problem as you. I found that the mamba_ssm installed in the conda environment needs to be replaced with the mamba_ssm in the official project of vision mamba. See the https://blog.csdn.net/weixin_45667052/article/details/136311600

I met the same problem as you. I found that the mamba_ssm installed in the conda environment needs to be replaced with the mamba_ssm in the official project of vision mamba. See the https://blog.csdn.net/weixin_45667052/article/details/136311600

**Comment by take-off-xyz** [comment]
@Charm11492 I have solved this problem, thank you so much !!!
Good luck to you !!!

**Comment by JerryBryant24** [comment]
> 我已经解决了这个问题，非常感谢!!祝你好运!
你好，请问你是怎么解决的

**Comment by take-off-xyz** [comment]
@JerryBryant24 上面兄弟发了一个教程链接，照着来就行：https://blog.csdn.net/weixin_45667052/article/details/136311600
原理应该是vim把mamba-ssm包里的东西改了，然后这个cdmamba应该是用的vim的，所有也需要用vim的包替换一下

**Comment by JerryBryant24** [comment]
window环境 还是ubuntu

**Comment by take-off-xyz** [comment]
@JerryBryant24 ubuntu呀，mamba不都是在linux下跑的嘛

**Comment by JerryBryant24** [comment]
> @JerryBryant24 ubuntu呀，mamba不都是在linux下跑的嘛

哈哈，我用的windows。我再试试。非常感谢！

**Comment by Sacrificeljj** [comment]
@take-off-xyz 您好，请问您装了vim的环境了吗，请问您的mmcv和mmseg是什么版本

**Comment by take-off-xyz** [comment]
@Sacrificeljj 没装vim的环境，就按上面链接的教程来的，然后缺什么包就按什么包。
我看了下mmcv==1.3.8，mmsegmentation==0.14.1

**Comment by Sacrificeljj** [comment]
@take-off-xyz 好的，感谢您

**Comment by Sacrificeljj** [comment]
@take-off-xyz 我成功跑起来了，感谢take-off老师，之前失败的原因是下载whl的时候我选成了含True的。
