### ISSUE TITLE
changemamba指标

### ISSUE THREAD

**Issue by absqh** [zmoka-zht/CDMamba#3]
Hello, I have a question. Why is the result so different from the original result of changemamba when comparing with changemamba? I used the changemamba model without pre-trained weights to run the LEVIR-CD+ dataset and there is also a difference between yours and the results

**Comment by zmoka-zht** [comment]
We use the Tiny version of changemamba (see CDMamba/models/mamba_cd.py for details).  To make a fair comparison, we unified the model into our framework for the experiment, without using any image enhancement methods, which may have led to different results. By the way, what can you achieve with F1 in the LEVIR-CD+ dataset?

**Comment by absqh** [comment]
The small model I use can reach 81.7%
