### ISSUE TITLE
载入权重时遇到问题

### ISSUE THREAD

**Issue by Sacrificeljj** [zmoka-zht/CDMamba#5]
作者您好，我在使用您提供的权重test的时候遇到了一些问题，想向您请教一下
![截屏2024-07-23 11 44 36](https://github.com/user-attachments/assets/aa321146-4c23-4107-9bb0-eaf83036025f)

**Comment by Sacrificeljj** [comment]
@zmoka-zht 好像没有正常载入

**Comment by Sacrificeljj** [comment]
@zmoka-zht  上述报错出现在对levir的权重进行测试时，我使用您提供的训练代码训练得到的权重文件使用test_cd.py进行测试没有报错
![截屏2024-07-23 13 50 30](https://github.com/user-attachments/assets/ee65ef4b-6461-48cc-92ae-751c9e9b13a4)
这是我训练时使用的默认模型参数
![截屏2024-07-23 13 51 02](https://github.com/user-attachments/assets/a05772dc-4f29-4ecd-8e6d-15999dba177a)请
是否是因为您提供的权重模型设置不同，麻烦您了，感谢您的工作

**Comment by Sacrificeljj** [comment]
> 十分感谢您的反馈。在代码公开时，为了方便阅读，我们整理了命名，这导致了公开的权重未正常加载。我们会及时修改这一问题。
感谢您的回复，请问这是否意味着短时间内如果我急需使用这些权重需要自己进行训练

**Comment by Sacrificeljj** [comment]
感谢您的回复，请问这是否意味着短时间内如果我急需使用这些权重需要自己进行训练

**Comment by zmoka-zht** [comment]
我们已经更新了权重链接：https://pan.baidu.com/s/1fSChP8BsK_Yy78GNNd3nzg 提取码：ckpt 
如果你觉得这个更新有所帮助，请给我们star，谢谢。

**Comment by Sacrificeljj** [comment]
非常感谢！您的更新对我的工作帮助很大！
祝好运！
