### ISSUE TITLE
Some questions about training

### ISSUE THREAD

**Issue by Krystal9999** [zmoka-zht/CDMamba#7]
我有几个问题想请教一下：
1、想问下12g的内存能满足复现要求吗？
2、对于训练的数据集有图像大小的要求吗？

**Comment by Krystal9999** [comment]
我是一张3060的显卡

**Comment by zmoka-zht** [comment]
Thank you for your attention. The image size is generally 256*256. A 12GB GPU can be used for training. If you find the answer helpful, please give us a star.
