### ISSUE TITLE
Dataset downloading is difficult

### ISSUE THREAD

**Issue by NgJun** [zmoka-zht/CDMamba#8]
Hello Team,

We are conducting experiments on change detection and would like to use the dataset splitting method (WHU, SYSU) as reported in your recent publication (CDMamba). However, downloading the datasets from PanBaidu is challenging for us without a Chinese phone number.

Do you have these split datasets available on another cloud platform (e.g., Mega, Google Drive, OneDrive)? If so, we would greatly appreciate it if you could share them with us. Thank you very much.

**Comment by zmoka-zht** [comment]
Thank you for your interest in our work. We've uploaded the dataset to Google Drive. If this helps you, please give us a star.
SYSU:https://drive.google.com/file/d/19VkVEWZx4f1byit56N90hmL15rll3UBi/view?usp=drive_link
WHU:https://drive.google.com/file/d/1gvPMZA_6WFSTgp40E1mSwrPfvIeZ1RpL/view?usp=drive_link

**Comment by NgJun** [comment]
Nice. Many thanks to you team.

**Comment by JoyLinWQ** [comment]
@zmoka-zht , could u please give access to me too? thanks!
